#action.yml
name: "Update conan center index"
description: "Create a version bump update for the conan center index for a specific recipe"
inputs:
  version: # id of input
    description: "the version to push"
    required: true
  fork_of_index:
    description: "The repository containing the fork"
    required: true
  recipe:
    description: "The recipe to update"
    required: true
  zipball_url:
    description: "The URL for the release zip ball to download"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--fork"
    - ${{ inputs.fork_of_index }}
    - "--version"
    - ${{ inputs.version }}
    - "--recipe"
    - ${{ inputs.recipe }}
    - "--zipball"
    - ${{ inputs.zipball_url }}
# todo update with upstream
# todo allow passing the fork as /bernedom/conan-center-index
